### ISSUE TITLE
Invalid npm module

### ISSUE THREAD

**Issue by DzmitryShylovich** [andyperlitch/ng2-super-table#2]
http://prntscr.com/c4686a this is how npm module looks like after installation

**Comment by andyperlitch** [comment]
hm that is definitely not how it should be, haha! I'll take a look today.

**Comment by andyperlitch** [comment]
@DzmitryShylovich can you try now with v0.1.1?

**Comment by DzmitryShylovich** [comment]
sure

**Comment by DzmitryShylovich** [comment]
ok, everything is fine now. thx.

but this is how [example](https://github.com/andyperlitch/ng2-super-table#installation) looks like http://prntscr.com/c4inet

**Comment by andyperlitch** [comment]
Ok, I'll take a look at what's going on there. In the meantime, [demo.ts](https://github.com/andyperlitch/ng2-super-table/blob/master/demo/demo.ts) will be much more useful to look at. Thanks again for the input, keep it coming.
