### ISSUE TITLE
Issue on using nge-super-table

### ISSUE THREAD

**Issue by AdrianPetri** [andyperlitch/ng2-super-table#5]
I am trying to integrate ng2-super-table into my angular2 application. I used the github for my source code: https://github.com/andyperlitch/ng2-super-table

The problem is that the directive tag is depracated in ES5.

@Component({
  selector: 'demo-app',
  directives: [SuperTable]
  .
  .
});
I searched on the Internet and it seems that i need to add the directive into declarations of the module like this:

@NgModule({
    imports: [RouterModule],
    declarations: [GridComponent, SuperTable],
    exports: [GridComponent]
})
The problem is that I still receive this error: Can't bind to 'tableclasses' since it isn't a known property of 'super-table'.

I mention the fact that I am new to angular2.

Can you please help me!

**Comment by andyperlitch** [comment]
This is because I have not updated it to work with @NgModules. Please take a look at #3, which I am hoping the community can help with.
